/**
 * @aiq.webdesigner
 * This script requires AIQ Web Designer
*/
setShadowDOM(true);
navigateTo("https://pfs-dev09.cbhzdev.com/NetMenu?application=mobilecardfile");
setValue(fallback(`textbox("Enter your user id.")`,
   `byXPath('//*[@id="userid"]')`,
   `textbox("form-control")`,
   `byXPath('//*[@name="UserId"]')`,
   `textbox("userid")`,
   `textbox("UserId")`,
   `byXPath('//*[@class="form-control"]')`,
   `byXPath('/html/body/div/div/div/form/div[2]/div/div/div/input')`,
   `byXPath("id('userid')")`,
   `byXPath("//input[@id='userid']")`,
   `textbox({'type':'text'})`,
   `byJQuery('input[title="Enter your user id."]')`,
   `byJQuery('div[class="form-horizontal"] > div[class="form-group"] > div[class="input-group "] > div[class="form-row"] > input[class="form-control"]')`,
   `byJQuery('#userid')`,
   `byJQuery('input[name="UserId"]')`,
   `byJQuery('input[value=""]')`),"ahm");
setValue(fallback(`password("Enter your password.")`,
   `byXPath('//*[@id="pwd"]')`,
   `password("form-control is-invalid")`,
   `byXPath('//*[@name="Password"]')`,
   `password("pwd")`,
   `password("Password")`,
   `byXPath('//*[@class="form-control is-invalid"]')`,
   `byXPath('/html/body/div/div/div/form/div[2]/div[2]/div/div/input')`,
   `byXPath("id('pwd')")`,
   `byXPath("//input[@id='pwd']")`,
   `password({'type':'password'})`,
   `byJQuery('input[title="Enter your password."]')`,
   `byJQuery('div[class="form-horizontal"] > div[class="form-group"] > div[class="input-group "] > div[class="form-row"] > input[class="form-control is-invalid"]')`,
   `byJQuery('#pwd')`,
   `byJQuery('input[name="Password"]')`),"init1");
click(fallback(`submit("Click to login to the application.")`,
   `byXPath('//*[@id="btnlogin"]')`,
   `submit("login-btn")`,
   `submit("btnlogin")`,
   `submit("Log In")`,
   `byXPath('//*[@class="login-btn"]')`,
   `byXPath('/html/body/div/div/div/form/div[3]/input')`,
   `byXPath("id('btnlogin')")`,
   `byXPath("//input[@id='btnlogin']")`,
   `submit({'type':'submit'})`,
   `byJQuery('input[title="Click to login to the application."]')`,
   `byJQuery('div[class="login-form-container"] > div[class="login-form"] > form[class=""] > div[class="form-row"] > input[class="login-btn"]')`,
   `byJQuery('#btnlogin')`,
   `byJQuery('input[value="Log In"]')`));
//click(fallback(`byXPath('//*[@id="forceLogin"]')`,
//   `byXPath('//*[@name="IsForceLoginChecked"]')`,
//   `checkbox("forceLogin")`,
//   `checkbox("IsForceLoginChecked")`,
//   `checkbox("true")`,
//   `byXPath('/html/body/div/div/div/form/div[3]/label/input')`,
//   `byXPath("id('forceLogin')")`,
//   `byXPath("//input[@id='forceLogin']")`,
//   `checkbox({'type':'checkbox'})`,
//   `byJQuery('#forceLogin')`,
//   `byJQuery('input[name="IsForceLoginChecked"]')`,
//   `byJQuery('input[value="true"]')`));
//click(fallback(`div("form-row[1]").xy(0.48, 0.50 )`,
//   `div("Password[2]").xy(0.48, 0.50 )`,
//   `byXPath('/html/body/div/div/div/form/div[2]/div[2]/div/div').xy(0.48, 0.50 )`,
//   `byXPath('//div/div[1]/div[1]/form/div[2]/div[2]/div/div').xy(0.48, 0.50 )`));
//setValue(fallback(`password("Enter your password.")`,
//   `byXPath('//*[@id="pwd"]')`,
//   `password("form-control")`,
//   `byXPath('//*[@name="Password"]')`,
//   `password("pwd")`,
//   `password("Password")`,
//   `byXPath('/html/body/div/div/div/form/div[2]/div[2]/div/div/input')`,
//   `byXPath("id('pwd')")`,
//   `byXPath("//input[@id='pwd']")`,
//   `password({'type':'password'})`,
//   `byJQuery('input[title="Enter your password."]')`,
//   `byJQuery('#pwd')`,
//   `byJQuery('input[name="Password"]')`),"init1");
//click(fallback(`submit("Click to login to the application.")`,
//   `byXPath('//*[@id="btnlogin"]')`,
//   `submit("login-btn")`,
//   `submit("btnlogin")`,
//   `submit("Log In")`,
//   `byXPath('//*[@class="login-btn"]')`,
//   `byXPath('/html/body/div/div/div/form/div[4]/input')`,
//   `byXPath("id('btnlogin')")`,
//   `byXPath("//input[@id='btnlogin']")`,
//   `submit({'type':'submit'})`,
//   `byJQuery('input[title="Click to login to the application."]')`,
//   `byJQuery('div[class="login-form-container"] > div[class="login-form"] > form[class=""] > div[class="form-row"] > input[class="login-btn"]')`,
//   `byJQuery('#btnlogin')`,
//   `byJQuery('input[value="Log In"]')`));
click(fallback(`byXPath('//*[@id="rcfLogOutButton"]')`,
   `button("btn btn-default btn-sm nav-btn[1]")`,
   `button("rcfLogOutButton")`,
   `button("Log Out")`,
   `byXPath('/html/body/section/nav/div/div[2]/ul[2]/li[3]/button')`,
   `byXPath("id('rcfLogOutButton')")`,
   `button(2, _in(div("rcfMainNavbarSupportedContent")))`,
   `button(2, _in(div({'id':'rcfMainNavbarSupportedContent'})))`,
   `byXPath("//button[@id='rcfLogOutButton']")`,
   `byJQuery('div[class="container-fluid pl-0 pr-0 bg-white shadow-sm"] > div[class="navbar-collapse collapse"] > ul[class="navbar-nav navbar-right"] > li[class="nav-item"] > button[class="btn btn-sm btn-default nav-btn"]')`,
   `byJQuery('#rcfLogOutButton')`));
